apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
    - port: 5000
      protocol: TCP
      name: tcp-app
      targetPort: 5000
      nodePort: 32500
  type: NodePort
