apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: local
  name: meu-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # Leitura/Escrita somente em 1 nรณ
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/local
  storageClassName: giropops

